version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cerebrium
    main: ./cmd/cerebrium
    binary: cerebrium
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Inject version information at build time
    ldflags:
      - -s -w
      - -X github.com/cerebriumai/cerebrium/internal/version.Version={{.Version}}
      - -X github.com/cerebriumai/cerebrium/internal/version.Commit={{.Commit}}
      - -X github.com/cerebriumai/cerebrium/internal/version.BuildDate={{.Date}}
      - -X github.com/cerebriumai/cerebrium/pkg/bugsnag.BugsnagAPIKey={{.Env.BUGSNAG_API_KEY}}
      - -X github.com/cerebriumai/cerebrium/pkg/bugsnag.DefaultReleaseStage=prod

# macOS Code Signing and Notarization
# This uses GoReleaser's cross-platform notarization with anchore/quill
# Prerequisites: Apple Developer account and certificates (see docs/SIGNING_SETUP.md)
notarize:
  macos:
    - # Only notarize if credentials are present (allows builds without signing in forks/local)
      enabled: '{{ isEnvSet "MACOS_CERTIFICATE_P12" }}'

      # IDs of binaries to sign and notarize (must match build id)
      ids:
        - cerebrium

      # Sign the binary with Developer ID certificate
      sign:
        # Base64-encoded P12 certificate
        certificate: "{{.Env.MACOS_CERTIFICATE_P12}}"

        # Password for the P12 certificate
        password: "{{.Env.MACOS_CERTIFICATE_PASSWORD}}"

        # Entitlements file (optional, defaults to none)
        # entitlements: ./entitlements.plist

      # Notarize using App Store Connect API
      notarize:
        # App Store Connect API Issuer ID
        issuer_id: "{{.Env.MACOS_NOTARIZATION_ISSUER_ID}}"

        # App Store Connect API Key ID
        key_id: "{{.Env.MACOS_NOTARIZATION_KEY_ID}}"

        # Base64-encoded .p8 API key
        key: "{{.Env.MACOS_NOTARIZATION_KEY}}"

        # Wait for notarization to complete
        wait: true

        # Timeout for notarization (Apple can be slow)
        timeout: 45m

archives:
  - id: cerebrium
    formats:
      - tar.gz
    name_template: >-
      cerebrium_cli_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    # Don't wrap in directory - binary goes at root of archive
    # This makes extraction simpler for Python wrapper and users
    wrap_in_directory: false
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "typo"

# Homebrew tap
brews:
  - name: cerebrium
    repository:
      owner: CerebriumAI
      name: homebrew-tap
      # Uses GITHUB_TOKEN by default, no need to specify
    homepage: https://www.cerebrium.ai
    description: CLI for deploying and managing Cerebrium apps
    license: MIT
    folder: Formula
    test: |
      system "#{bin}/cerebrium version"

# Linux packages
nfpms:
  - id: cerebrium
    package_name: cerebrium
    homepage: https://www.cerebrium.ai
    maintainer: Cerebrium AI <support@cerebrium.ai>
    description: CLI for deploying and managing Cerebrium apps
    license: MIT

    # Debian/Ubuntu (apt)
    formats:
      - deb
      - rpm

    # Dependencies
    dependencies: []

    # Binary name
    bindir: /usr/bin

# GitHub Release
release:
  github:
    owner: CerebriumAI
    name: cerebrium
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
# Docker images (optional)
# dockers:
#   - image_templates:
#       - "cerebriumai/cerebrium:{{ .Version }}"
#       - "cerebriumai/cerebrium:latest"
#     dockerfile: Dockerfile
