branches:
  - feat/automated-releases  # Test on current branch

plugins:
  # Analyze commits to determine version bump
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: patch
        - breaking: true
          release: major

  # Generate release notes
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "✨ Features"
          - type: fix
            section: "🐛 Bug Fixes"

  # Write version to file (for testing)
  - - "@semantic-release/exec"
    - prepareCmd: |
        echo "Would release version: ${nextRelease.version}"
        echo "From: ${lastRelease.version || 'initial'}"
        echo "Type: ${nextRelease.type}"
