branches:
  - main
  - master
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  # Analyze commits to determine version bump
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: patch
        # Breaking changes trigger major version
        - breaking: true
          release: major
        # No release for these types
        - type: docs
          release: false
        - type: style
          release: false
        - type: chore
          release: false
        - type: refactor
          release: false
        - type: test
          release: false
        - type: build
          release: false
        - type: ci
          release: false

  # Generate release notes
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "âœ¨ Features"
          - type: fix
            section: "ðŸ› Bug Fixes"
          - type: perf
            section: "âš¡ Performance Improvements"
          - type: revert
            section: "âª Reverts"
          - type: docs
            section: "ðŸ“š Documentation"
            hidden: false
          - type: refactor
            section: "â™»ï¸ Code Refactoring"
            hidden: false
          - type: chore
            hidden: true
          - type: style
            hidden: true
          - type: test
            hidden: true
          - type: build
            hidden: true
          - type: ci
            hidden: true

  # Update version in Go files
  - - "@semantic-release/exec"
    - prepareCmd: |
        echo "${nextRelease.version}" > VERSION
        # Update version in Go code if needed
        sed -i "s/Version = \".*\"/Version = \"${nextRelease.version}\"/" internal/version/version.go || true

  # Commit changes
  - - "@semantic-release/git"
    - assets:
        - VERSION
        - internal/version/version.go
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  # Create GitHub release and tag
  - - "@semantic-release/github"
    - successComment: false
      failComment: false
      releasedLabels:
        - released
        - "released-v${nextRelease.version}"
      # This will create the GitHub release which triggers:
      # 1. release.yml workflow (via tag push) -> GoReleaser -> Homebrew
      # 2. pypi-publish.yml workflow (via release event) -> PyPI
