// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/cerebriumai/cerebrium/internal/wsapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// StreamBuildLogs provides a mock function for the type MockClient
func (_mock *MockClient) StreamBuildLogs(ctx context.Context, projectID string, buildID string, callback func(wsapi.BuildLogMessage) error) error {
	ret := _mock.Called(ctx, projectID, buildID, callback)

	if len(ret) == 0 {
		panic("no return value specified for StreamBuildLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, func(wsapi.BuildLogMessage) error) error); ok {
		r0 = returnFunc(ctx, projectID, buildID, callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StreamBuildLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamBuildLogs'
type MockClient_StreamBuildLogs_Call struct {
	*mock.Call
}

// StreamBuildLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - buildID string
//   - callback func(wsapi.BuildLogMessage) error
func (_e *MockClient_Expecter) StreamBuildLogs(ctx interface{}, projectID interface{}, buildID interface{}, callback interface{}) *MockClient_StreamBuildLogs_Call {
	return &MockClient_StreamBuildLogs_Call{Call: _e.mock.On("StreamBuildLogs", ctx, projectID, buildID, callback)}
}

func (_c *MockClient_StreamBuildLogs_Call) Run(run func(ctx context.Context, projectID string, buildID string, callback func(wsapi.BuildLogMessage) error)) *MockClient_StreamBuildLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 func(wsapi.BuildLogMessage) error
		if args[3] != nil {
			arg3 = args[3].(func(wsapi.BuildLogMessage) error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_StreamBuildLogs_Call) Return(err error) *MockClient_StreamBuildLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StreamBuildLogs_Call) RunAndReturn(run func(ctx context.Context, projectID string, buildID string, callback func(wsapi.BuildLogMessage) error) error) *MockClient_StreamBuildLogs_Call {
	_c.Call.Return(run)
	return _c
}
