name: Test

on:
  pull_request:
    branches: [main, development]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.25.x']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure Git line endings
        # Ensure .gitattributes rules are respected on all platforms
        # This is critical for golden test files to work on Windows
        run: git config --global core.autocrlf false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -race -shuffle=on ./...
